Thebox/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('tools.urls')),
    # path('test', include('tools.urls')),
    path('task/', include('task.urls')),
    path('ptt/', include('myptt.urls')),
    path('stock/', include('stock.urls')),
    path('spider/', include('spider.urls'))
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
  path('', views.index, name='index'),
  path('show/<int:pk>', views.show_item, name='show_item'),
  path('delete_item', views.delete_item, name='delete_item'),

  path('insert_content', views.insert_content, name='insert_content'),

  # path('item/<str:item>', views.to_index, name='to_index'),
]

task/models.py
from typing import cast
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField, TextField, IntegerField
# Create your models here.

class Sort(models.Model): 
  item = models.CharField(max_length=64)
  detail = models.TextField(null=True)
  order = models.IntegerField()
  created_at = models.DateTimeField(auto_now_add=True)
  modified_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f'{self.item}({self.order})'

# class Detail(models.Model):
#   sorts = models.ForeignKey(Sort, on_delete=models.CASCADE, related_name="sort")
#   content = models.TextField()
#   created_at = models.DateTimeField(auto_now_add=True)
#   modified_at = models.DateTimeField(auto_now=True)

task/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, resolve_url, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
from .form import SortModelForm
from .models import Sort
# Create your views here.


def index(request, item = ''):
  sort = Sort.objects.all()
  default_item = sort.first().item
  form = SortModelForm()
  if request.method == 'POST':
    # request.POST['order'] = 5;
    next_order = len(Sort.objects.all()) + 1
    sort = Sort(order = next_order)
    form = SortModelForm(request.POST, instance=sort)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect(reverse('task:index'))
  
  
  return render(request, 'task/index.html', {
    'form' : form,
    'sort' : sort,
    'default': sort.first()
  })

def show_item(request, pk):
  sort = Sort.objects.get(pk=pk)
  return render(request, 'task/section.html', {
    'sort': sort
  })

def delete_item(request):
  pk = request.GET['pk']
  Sort.objects.get(pk=pk).delete()
  return HttpResponse(f'Delete {pk}')

def insert_content(request):
  sort = Sort.objects.get(pk=request.POST['pk'])
  sort.detail = request.POST['html']
  sort.save()
  return HttpResponse(sort)
  # print(request.POST)
  
  

# def to_index(request, item):
#   return redirect('task:index')

task/templates/task/index.html
{% extends 'task/layout.html' %}
{% load static %} {% load sass_tags %}


{% block nav %}
{% include 'nav.html' %}
{% endblock %}

{% block main %}
{% include 'task/main.html' %}
{% endblock %}

{% block script %}
<script>
  const url_index = "{% url 'task:index' %}";
  const url_delete_item = "{% url 'task:delete_item' %}";
  const url_insert_content = "{% url 'task:insert_content' %}";
  const csrf = '{{ csrf_token }}';
</script>
<script type="module" src="{% static 'task/js/base.js' %}"></script>
{% endblock %}

task/templates/task/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-tw">

<head>
  {% load sass_tags %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Task</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{% sass_src 'task/scss/style.scss' %}" type="text/css">
  <link rel="stylesheet" href="{% sass_src 'nav.scss' %}" type="text/css">
  {% block css %}
  {% endblock %}
</head>

<body>
  <div id="container">
    <header>
      {% block nav %}
      {% endblock %}
    </header>
    {% block main %}
    {% endblock %}
    <footer>
      @2021 -
    </footer>
  </div>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock %}
</body>

</html>

task/templates/task/main.html
<aside class="sidebar">    
  <form action="{% url 'task:index' %}" method="POST">
    {% csrf_token %}
    {{ form.item }}
    <input type="submit" value="新增">
  </form>
  <div class="sort" data-sort-item>
    <ul>
      {% for s in sort %}
        <li id="{{ s.id }}" data-item="{{ s.item }}" data-sort="{{ s.order }}" class="sort__item flex-row-center">{{ s.item }}
          <span data-id="{{ s.id }}" class="material-icons icon-delete">delete</span>
        </li>
      {% endfor %}
    </ul>
  </div>   
</aside>
<section>
  {% include 'task/section.html' %}
</section>

task/templates/task/nav.html
<nav>
  <div class="manage">
    <a href="{% url 'admin:index' %}">後台管理</a>
  </div>
</nav>

task/templates/task/section.html
<h1 class="heading">{% firstof sort.item default.item  %}</h1>
<!-- <div class="tool">編輯<span class="material-icons icon-edit">edit</span></div> -->
<div id="content">{% firstof sort.detail default.detail  %}</div>

<div class="operate">
  {% csrf_token %}
  <a data-pk="{% firstof sort.pk default.pk  %}" href="#" class="confirm">確定</a>
</div>