Thebox/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('tools.urls')),
    # path('test', include('tools.urls')),
    path('task/', include('task.urls')),
    path('ptt/', include('myptt.urls')),
    path('stock/', include('stock.urls')),
    path('spider/', include('spider.urls'))
]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'
urlpatterns = [
    path('', views.index, name='index'),
    path('file', views.file, name='file'),    
    path('test', views.test, name='test'),    
    path('db_read_tire', views.db_read_tire, name='db_read_tire'),    
    path('db_update_tire', views.db_update_tire, name='db_update_tire'),
    path('insert_tire', views.insert_tire, name='insert_tire'),
    path('f', views.f, name='f')
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
  path('', views.index, name='index'),
  path('show/<int:pk>', views.show_item, name='show_item'),
  path('delete_item', views.delete_item, name='delete_item'),

  path('insert_content', views.insert_content, name='insert_content'),

  # path('item/<str:item>', views.to_index, name='to_index'),
]

stock/models.py
from enum import auto
from django.db import models
from django.db.models.fields.related import create_many_to_many_intermediary_model

# Create your models here.

TIRE_CHOICES = [('null', 'null')]
for n in range(20):
    TIRE_CHOICES.append((n, n))
tuple(TIRE_CHOICES)

class TireManager(models.Manager):
    def create_inch(self, inch):
        obj = self.create(inch=inch)
        return obj


class TireInch(models.Model):
    class Meta:
        ordering = ['inch']
    inch = models.CharField(max_length=64)
    created_at = models.DateTimeField(auto_now=True)
    modified_at = models.DateTimeField(auto_now=True)

    objects = TireManager()

    def __str__(self):
        return self.inch

class Tire(models.Model):
    class Meta:
        ordering = ('spec',)
    spec = models.CharField(max_length=64)
    tire_inch = models.ForeignKey(
        TireInch, on_delete=models.CASCADE, related_name='tire_inch')
    quantity = models.CharField(max_length=4, choices=TIRE_CHOICES, default="null", null=True)
    # quantity = models.PositiveSmallIntegerField(null=True)
    created_at = models.DateTimeField(auto_now=True)
    modified_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.spec}'

class Recent(models.Model):
    tire_spec = models.ForeignKey(Tire, on_delete=models.CASCADE, related_name='tire_spec')
    before = models.IntegerField()
    after = models.IntegerField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.tire_spec} 前: {self.before} 後: {self.after}'

stock/views.py
import csv
from os import kill
import re
import json 
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, request
from django.urls import reverse
from django.core import serializers

from Thebox.components import Components


# Create your views here.

from .models import Tire, TireInch, Recent
from .form import TireModelForm

def parse_csv_string(csv_string):
    lines = csv_string.splitlines()
    reader = csv.reader(lines)
    parsed_csv = list(reader)
    tire_dict = {}
    for row in parsed_csv:
        for key, item in enumerate(row):
            if len(item) >= 3 and re.findall(r'-', item):
                item  = re.sub(r'(\d+)[-|/](\d+)[-|/](\d+)', r'\1/\2-\3', item)    
                inch = item[-2:]
                num =  row[key+1] or 'null'
                spec_tuple = (item, num)
                if(tire_dict.get(inch) is None):
                    tire_dict[inch] = [spec_tuple]
                else:
                    tire_dict[inch].append(spec_tuple)

    # tire_dict = {}

    # tires_key = sorted(list(tires.keys()), reverse=True)
    # for index, key in enumerate(tires_key):
    #     tire_dict[key] = tires[key]
    
    return tire_dict

def index(request):
    if(request.method == "POST"):
        form = TireModelForm(request.POST)
        if(form.is_valid()):
            form.save()
        return HttpResponseRedirect(reverse('stock:index'))
    inches = TireInch.objects.all()
    tires = Tire.objects.all()
    form = TireModelForm()
    recents = Recent.objects.all().order_by('-created_at')
    print(recents)
    return render(request, 'stock/index.html', {
        "inches": inches,
        "tires": tires,
        "form": form,
        "recents": recents
    })

# stock/file
def file(request):
    return render(request, 'stock/file.html', {
    })

def test(request):
    csv_string = request.GET['csv'] 
    results = parse_csv_string(csv_string)
    return HttpResponse( json.dumps(results, indent=4) )


def insert_tire(request):
    csv_string = request.GET['csv'] 
    tire_dict = parse_csv_string(csv_string)
    for k, v_list in tire_dict.items():
        for v in v_list:   
            # ti = TireInch.objects.get(inch=k)
            t = Tire.objects.filter(spec=v[0]).update(quantity=v[1])
    return HttpResponse('ok')

def db_read_tire(request):
    inch_id = request.GET['inch_id']
    ti = TireInch.objects.get(pk=inch_id)
    tires = ti.tire_inch.all()
    html = [
       {"class": ''},
       [
           {"tag": "span", "class": "spec", "key": 'spec'},
           {"tag": "span", "class": "quantity", "key": 'quantity'}
       ]     
    ]
    elemnt = Components().ul_li(list(tires), *html)
    return HttpResponse(elemnt)
    # res = serializers.serialize("json", tires)
    # return HttpResponse(res, content_type="application/json" )

def db_update_tire(request):
    spec = request.GET['spec']
    quantity = request.GET['quantity']
    before = request.GET['before']
    t = Tire.objects.get(spec=spec)
    t.quantity = quantity
    t.save()
    r = Recent.objects.create(tire_spec=t, before=before, after=quantity)
    return HttpResponse( json.dumps([spec, quantity]) )


def f(request):
    t = Tire.objects.filter(quantity='null').update(quantity='0')
    return HttpResponse('ok')

stock/templates/stock/file.html
{% extends 'stock/layout.html' %}
{% load static %}

{% block main %}
<form action="">
    <input type="file" name="uplaoded_file" class="fileUploader" data-url="{% url 'stock:test' %}">
</form>
<button class="js-insert-tire" data-url="{% url 'stock:test' %}">執行</button>
<pre>
    <div id="fileContent"></div>
</pre>
{% endblock %}

{% block script %}

<script type="module" src="{% static 'stock/js/file.js' %}">
  
</script>
{% endblock%}

stock/templates/stock/index.html
{% extends 'stock/layout.html' %}
{% load static %} {% load sass_tags %}
{% block css %}
<link rel="stylesheet" href="{% sass_src 'scss/global.scss' %}" type="text/css">
<link rel="stylesheet" href="{% sass_src 'stock/scss/style.scss' %}" type="text/css">
{% endblock %}

{% block nav %}
{% include 'nav.html' %}
{% endblock %}

{% block main %}
{% include 'stock/main.html' %}
{% endblock %}

{% block script %}
<script type="module" src="{% static 'stock/js/index.js' %}?version=1"></script>
{% endblock %}

stock/templates/stock/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-tw">

<head>
    {% load sass_tags %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>

<body>
    <div id="container">
        {# <div class="mask"></div> #}
        <header>
            {% block nav %}
            {% endblock %}
        </header>
        {% block main %}
        {% endblock %}
        <footer>
            @2021 -
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>

</html>

stock/templates/stock/main.html
<main>
    <aside>
    </aside>
    <section>
        {% csrf_token %}
        <!-- {{ form.tire_inch.label }}
            {{ form.tire_inch }} -->
        <div class="nav_inch">
            <ul class="ul_inch">
                {% for inch in inches %}
                <li data-id="{{ inch.id }}" data-url="{% url 'stock:db_read_tire' %}" data-tap=".tire__spec">
                    {{ inch.inch }}
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="tire">
            <div class="tire__spec"></div>
            <div class="modify">
                <form class="modifyform" action="" method="GET">
                    <div class="modifyform__close">X</div>
                    <div class="modifyform__spec"></div>
                    <div>修改前:<span class="modifyform__before"></span></div>
                    <div>
                        <label for="modifyform__quantity">修改後</label>
                        <input type="text" name="modifyform__quantity" class="modifyform__quantity">
                        <input type="submit" value="修改" data-url="{% url 'stock:db_update_tire' %}"
                            class="modifyform__submit">
                    </div>
                </form>
            </div>
        </div>
        <div class="recent">
            <h2>最近更新</h2>
            {% for recent in recents %}
            <p>{{ recent }}</p>
            {% empty %}
            <p>No recent record</p>
            {% endfor %}
        </div>
    </section>
</main>