Thebox/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('tools.urls')),
    # path('test', include('tools.urls')),
    path('task/', include('task.urls')),
    path('ptt/', include('myptt.urls')),
    path('stock/', include('stock.urls')),
    path('spider/', include('spider.urls'))
]

myptt/urls.py
from django.urls import path
from . import views

app_name = 'myptt'
urlpatterns = [
    path('', views.index, name="index")
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
  path('', views.index, name='index'),
  path('show/<int:pk>', views.show_item, name='show_item'),
  path('delete_item', views.delete_item, name='delete_item'),

  path('insert_content', views.insert_content, name='insert_content'),

  # path('item/<str:item>', views.to_index, name='to_index'),
]

myptt/models.py
from django.db import models

# Create your models here.

myptt/views.py
from django.http.response import HttpResponse
import sys
from django.shortcuts import render
from PyPtt import PTT

ptt_id = 'chin2049 '
password = '19813031'
board = 'Gossiping'


# Create your views here.

def index(request):
    ptt_bot = PTT.API()
    ptt_bot.login(ptt_id, password)
    num = int(request.GET['quantity'])
    posts = []
    index = get_index(ptt_bot)
    ptt_time = ptt_bot.get_time()
    for i in range(num):
        posts.append(ptt_bot.get_post(
            board,
            post_index=index))
        index -= 1
    ptt_bot.logout()
    return render(request, 'myptt/index.html', {
        "ptt": ptt_bot,
        "posts": posts,
        "time": ptt_time
    })


def get_index(ptt_bot):
    index = ptt_bot.get_newest_index(
        PTT.data_type.index_type.BBS,
        board=board
    )
    return index

myptt/templates/myptt/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <!-- <script src="{% static 'myptt/js/index.js' %}" defer></script> -->
</head>

<body>
  <!-- <h1>{{ ptt }}</h1> -->
  <form action="{% url 'myptt:index' %}" method="GET">
    <label for="num">搜尋篇數</label><input type="text" name="quantity">
    <input type="submit" value="搜尋">
  </form>
  <div>PTT TIME: {{ time }}</div>
  <div>最新</div>
  <ul>
    {% for post in posts %}
      <li>{{ post.title }}</li>
    {% endfor %}
  </ul>
  
</body>

</html>