Thebox/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('tools.urls')),
    # path('test', include('tools.urls')),
    path('task/', include('task.urls')),
    path('ptt/', include('myptt.urls')),
    path('stock/', include('stock.urls')),
    path('spider/', include('spider.urls'))
]

stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'
urlpatterns = [
    path('', views.index, name='index'),
    path('file', views.file, name='file'),    
    path('test', views.test, name='test'),    
    path('db_read_tire', views.db_read_tire, name='db_read_tire'),    
    path('db_update_tire', views.db_update_tire, name='db_update_tire'),
    path('insert_tire', views.insert_tire, name='insert_tire'),
    path('f', views.f, name='f')
]

task/urls.py
from django.urls import path
from . import views

app_name = 'task'
urlpatterns = [
  path('', views.index, name='index'),
  path('show/<int:pk>', views.show_item, name='show_item'),
  path('delete_item', views.delete_item, name='delete_item'),

  path('insert_content', views.insert_content, name='insert_content'),

  # path('item/<str:item>', views.to_index, name='to_index'),
]

templates/nav.html
<nav>
    <div class="logo"></div>
    <ul class="navbar">
        <li>
            <a href="{% url 'task:index' %}">Task</a>
        </li>
        <li>
            <a href="{% url 'stock:index' %}">Stock</a>
        </li>
    </ul>
    <p class="manage">
        <a class="admin" href="{% url 'admin:index' %}">後台管理</a>
    </p>
</nav>